spring.application.name=SlideHub
server.port=8080

#  Configuracion del GATEWAY  
spring.cloud.gateway.routes.id=ai-service-route
spring.cloud.gateway.routes.uri=lb://ai-service
spring.cloud.gateway.routes.predicates=path=/api/ai/**
# Ruta para el microservicio de IA
spring.cloud.gateway.routes.filters=StripPrefix=2

# Ruta general para los demas microservicios
spring.cloud.gateway.routes.id=default-route
spring.cloud.gateway.routes.uri=lb://other-service
spring.cloud.gateway.routes.predicates=Path=/api/**